# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calculator_pb2 as calculator__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in calculator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdvancedCalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/calculator.AdvancedCalculator/Add',
                request_serializer=calculator__pb2.BinaryOpRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalculatorResponse.FromString,
                _registered_method=True)
        self.Divide = channel.unary_unary(
                '/calculator.AdvancedCalculator/Divide',
                request_serializer=calculator__pb2.BinaryOpRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalculatorResponse.FromString,
                _registered_method=True)
        self.Factorial = channel.unary_unary(
                '/calculator.AdvancedCalculator/Factorial',
                request_serializer=calculator__pb2.UnaryOpRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalculatorResponse.FromString,
                _registered_method=True)
        self.Fibonacci = channel.unary_unary(
                '/calculator.AdvancedCalculator/Fibonacci',
                request_serializer=calculator__pb2.UnaryOpRequest.SerializeToString,
                response_deserializer=calculator__pb2.CalculatorResponse.FromString,
                _registered_method=True)


class AdvancedCalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Divide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Factorial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fibonacci(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdvancedCalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=calculator__pb2.BinaryOpRequest.FromString,
                    response_serializer=calculator__pb2.CalculatorResponse.SerializeToString,
            ),
            'Divide': grpc.unary_unary_rpc_method_handler(
                    servicer.Divide,
                    request_deserializer=calculator__pb2.BinaryOpRequest.FromString,
                    response_serializer=calculator__pb2.CalculatorResponse.SerializeToString,
            ),
            'Factorial': grpc.unary_unary_rpc_method_handler(
                    servicer.Factorial,
                    request_deserializer=calculator__pb2.UnaryOpRequest.FromString,
                    response_serializer=calculator__pb2.CalculatorResponse.SerializeToString,
            ),
            'Fibonacci': grpc.unary_unary_rpc_method_handler(
                    servicer.Fibonacci,
                    request_deserializer=calculator__pb2.UnaryOpRequest.FromString,
                    response_serializer=calculator__pb2.CalculatorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.AdvancedCalculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculator.AdvancedCalculator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdvancedCalculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculator.AdvancedCalculator/Add',
            calculator__pb2.BinaryOpRequest.SerializeToString,
            calculator__pb2.CalculatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Divide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculator.AdvancedCalculator/Divide',
            calculator__pb2.BinaryOpRequest.SerializeToString,
            calculator__pb2.CalculatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Factorial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculator.AdvancedCalculator/Factorial',
            calculator__pb2.UnaryOpRequest.SerializeToString,
            calculator__pb2.CalculatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fibonacci(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculator.AdvancedCalculator/Fibonacci',
            calculator__pb2.UnaryOpRequest.SerializeToString,
            calculator__pb2.CalculatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
