# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"\'\n\x0f\x42inaryOpRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"\x1b\n\x0eUnaryOpRequest\x12\t\n\x01n\x18\x01 \x01(\x05\"$\n\x12\x43\x61lculatorResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32\xb9\x02\n\x12\x41\x64vancedCalculator\x12\x44\n\x03\x41\x64\x64\x12\x1b.calculator.BinaryOpRequest\x1a\x1e.calculator.CalculatorResponse\"\x00\x12G\n\x06\x44ivide\x12\x1b.calculator.BinaryOpRequest\x1a\x1e.calculator.CalculatorResponse\"\x00\x12I\n\tFactorial\x12\x1a.calculator.UnaryOpRequest\x1a\x1e.calculator.CalculatorResponse\"\x00\x12I\n\tFibonacci\x12\x1a.calculator.UnaryOpRequest\x1a\x1e.calculator.CalculatorResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BINARYOPREQUEST']._serialized_start=32
  _globals['_BINARYOPREQUEST']._serialized_end=71
  _globals['_UNARYOPREQUEST']._serialized_start=73
  _globals['_UNARYOPREQUEST']._serialized_end=100
  _globals['_CALCULATORRESPONSE']._serialized_start=102
  _globals['_CALCULATORRESPONSE']._serialized_end=138
  _globals['_ADVANCEDCALCULATOR']._serialized_start=141
  _globals['_ADVANCEDCALCULATOR']._serialized_end=454
# @@protoc_insertion_point(module_scope)
